In [737]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [738]:
people['email']

['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [739]:
import pandas as pd

In [740]:
df = pd.DataFrame(people)

In [741]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [742]:
type(df['email'])

pandas.Series

In [743]:
df[['last', 'email']]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [744]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [745]:
df.iloc[[0,1],[1,2]]

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com

In [746]:
df.reset_index()

   index  first     last                    email
0      0  Corey  Schafer  CoreyMSchafer@gmail.com
1      1   Jane      Doe        JaneDoe@email.com
2      2   John      Doe        JohnDoe@email.com

In [747]:
df.set_index('first')

          last                    email
first
Corey  Schafer  CoreyMSchafer@gmail.com
Jane       Doe        JaneDoe@email.com
John       Doe        JohnDoe@email.com

In [748]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [749]:
df.set_index('first', inplace = True)

In [750]:
df

          last                    email
first
Corey  Schafer  CoreyMSchafer@gmail.com
Jane       Doe        JaneDoe@email.com
John       Doe        JohnDoe@email.com

In [751]:
df.reset_index()

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [752]:
df

          last                    email
first
Corey  Schafer  CoreyMSchafer@gmail.com
Jane       Doe        JaneDoe@email.com
John       Doe        JohnDoe@email.com

In [753]:
df.reset_index(inplace = True)

In [754]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [755]:
filt = (df['last'] == 'Doe') | (df['first'] == 'john')

In [756]:
df.loc[filt, 'email']

1    JaneDoe@email.com
2    JohnDoe@email.com
Name: email, dtype: str

In [757]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [758]:
df.columns = (x.upper() for x in df.columns)
df

   FIRST     LAST                    EMAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [759]:
df.rename(columns= {'FIRST':'first'})

   first     LAST                    EMAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [760]:
df

   FIRST     LAST                    EMAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [761]:
df.columns.str.lower()

Index(['first', 'last', 'email'], dtype='str')

In [762]:
df

   FIRST     LAST                    EMAIL
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [763]:
df.columns = (x.lower() for x in df.columns)

In [764]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [765]:
df.loc[3] = ['anna','beckham','anna34@email.com']

In [766]:
df.replace({'John' : 'Johnny'},inplace=True)

    first     last                    email
0   Corey  Schafer  CoreyMSchafer@gmail.com
1    Jane      Doe        JaneDoe@email.com
2  Johnny      Doe        JohnDoe@email.com
3    anna  beckham         anna34@email.com

In [767]:
df

    first     last                    email
0   Corey  Schafer  CoreyMSchafer@gmail.com
1    Jane      Doe        JaneDoe@email.com
2  Johnny      Doe        JohnDoe@email.com
3    anna  beckham         anna34@email.com

In [768]:
df.loc[2,'first'] = 'John'

In [769]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   anna  beckham         anna34@email.com

In [770]:
df.drop(3)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [771]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com
3   anna  beckham         anna34@email.com

In [772]:
df.email = df.email.str.lower()

In [773]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John      Doe        johndoe@email.com
3   anna  beckham         anna34@email.com

In [774]:
df.email.apply(len)

0    23
1    17
2    17
3    16
Name: email, dtype: int64

In [775]:
def update_email(email) :
    return email.upper()

In [776]:
df.email = df.email.apply(update_email)

In [777]:
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane      Doe        JANEDOE@EMAIL.COM
2   John      Doe        JOHNDOE@EMAIL.COM
3   anna  beckham         ANNA34@EMAIL.COM

In [778]:
df.email = df.email.apply(lambda x : x.lower())

In [779]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John      Doe        johndoe@email.com
3   anna  beckham         anna34@email.com

In [780]:
df.apply(len, axis = 'columns')

0    3
1    3
2    3
3    3
dtype: int64

In [781]:
df.map(len)

   first  last  email
0      5     7     23
1      4     3     17
2      4     3     17
3      4     7     16

In [782]:
df.map(str.lower)

   first     last                    email
0  corey  schafer  coreymschafer@gmail.com
1   jane      doe        janedoe@email.com
2   john      doe        johndoe@email.com
3   anna  beckham         anna34@email.com

In [783]:
df.first.map({'Corey':'chris'})

0    chris
1      NaN
2      NaN
3      NaN
Name: first, dtype: str

In [784]:
df

   first     last                    email
0  Corey  Schafer  coreymschafer@gmail.com
1   Jane      Doe        janedoe@email.com
2   John      Doe        johndoe@email.com
3   anna  beckham         anna34@email.com

In [785]:
df['full_name'] = df.first + ' ' + df.last

In [786]:
df

   first     last                    email      full_name
0  Corey  Schafer  coreymschafer@gmail.com  Corey Schafer
1   Jane      Doe        janedoe@email.com       Jane Doe
2   John      Doe        johndoe@email.com       John Doe
3   anna  beckham         anna34@email.com   anna beckham

In [787]:
df.drop(columns=['first','last'], inplace=True)

In [788]:
df

                     email      full_name
0  coreymschafer@gmail.com  Corey Schafer
1        janedoe@email.com       Jane Doe
2        johndoe@email.com       John Doe
3         anna34@email.com   anna beckham

In [789]:
df['full_name'].str.split(' ', expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe
3   anna  beckham

In [790]:
df[['first','last']] = df['full_name'].str.split(' ', expand=True)

In [791]:
df

                     email      full_name  first     last
0  coreymschafer@gmail.com  Corey Schafer  Corey  Schafer
1        janedoe@email.com       Jane Doe   Jane      Doe
2        johndoe@email.com       John Doe   John      Doe
3         anna34@email.com   anna beckham   anna  beckham

In [792]:
col1 = df.pop('first')
df.insert(0,'first',col1)

In [793]:
df

   first                    email      full_name     last
0  Corey  coreymschafer@gmail.com  Corey Schafer  Schafer
1   Jane        janedoe@email.com       Jane Doe      Doe
2   John        johndoe@email.com       John Doe      Doe
3   anna         anna34@email.com   anna beckham  beckham

In [794]:
col2 = df.pop('last')
df.insert(1,'last',col2)

In [795]:
df

   first     last                    email      full_name
0  Corey  Schafer  coreymschafer@gmail.com  Corey Schafer
1   Jane      Doe        janedoe@email.com       Jane Doe
2   John      Doe        johndoe@email.com       John Doe
3   anna  beckham         anna34@email.com   anna beckham

In [796]:
df.replace({'anna':'Anna'},inplace=True)

   first     last                    email      full_name
0  Corey  Schafer  coreymschafer@gmail.com  Corey Schafer
1   Jane      Doe        janedoe@email.com       Jane Doe
2   John      Doe        johndoe@email.com       John Doe
3   Anna  beckham         anna34@email.com   anna beckham

In [797]:
df.sort_values(by = ['last'],ascending=[True])

   first     last                    email      full_name
1   Jane      Doe        janedoe@email.com       Jane Doe
2   John      Doe        johndoe@email.com       John Doe
0  Corey  Schafer  coreymschafer@gmail.com  Corey Schafer
3   Anna  beckham         anna34@email.com   anna beckham

In [798]:
df

   first     last                    email      full_name
0  Corey  Schafer  coreymschafer@gmail.com  Corey Schafer
1   Jane      Doe        janedoe@email.com       Jane Doe
2   John      Doe        johndoe@email.com       John Doe
3   Anna  beckham         anna34@email.com   anna beckham

In [799]:
df.sort_values(by=['first','last'],ascending=[True, False],inplace=True)

In [800]:
df

   first     last                    email      full_name
3   Anna  beckham         anna34@email.com   anna beckham
0  Corey  Schafer  coreymschafer@gmail.com  Corey Schafer
1   Jane      Doe        janedoe@email.com       Jane Doe
2   John      Doe        johndoe@email.com       John Doe

In [801]:
df.sort_index(inplace=True)

In [802]:
df

   first     last                    email      full_name
0  Corey  Schafer  coreymschafer@gmail.com  Corey Schafer
1   Jane      Doe        janedoe@email.com       Jane Doe
2   John      Doe        johndoe@email.com       John Doe
3   Anna  beckham         anna34@email.com   anna beckham

In [803]:
df.last.sort_values()

1        Doe
2        Doe
0    Schafer
3    beckham
Name: last, dtype: str

In [807]:
last_group = df.groupby('last')

In [808]:
last_group.groups

{'Doe': [1, 2], 'Schafer': [0], 'beckham': [3]}

In [809]:
last_group.get_group('Doe')

  first last              email full_name
1  Jane  Doe  janedoe@email.com  Jane Doe
2  John  Doe  johndoe@email.com  John Doe

In [812]:
last_group['full_name'].value_counts